### ISSUE TITLE
Install Neural Style on AWS instance

### ISSUE THREAD

**Issue by deepiksdev** [deepiksdev/torch#1]
https://github.com/jcjohnson/neural-style

cc @lolitawxc

**Comment by deepiksdev** [comment]
See https://github.com/deepiksdev/tensorflow/issues/32

**Comment by deepiksdev** [comment]
@Lolitawxc 

> I created an AMI with functionnal Neural Style (not a server yet): ami-9ae9668d
I tried with an image of 600 * 450 pixels as content and an image of 468 * 600 as style and
it took about 8min30.

I am surprised it takes so much time. Are sure you are using GPU? How does it compare with the time on your local device?

**Comment by Lolitawxc** [comment]
>I am surprised it takes so much time. Are sure you are using GPU? How does it compare with the time on your local device?

I launched it on the local machine (but on a smaller style image) and it took 2min30.
Maybe when you launched it, it was on smaller images ? or a g8*8 instance instead of a g2*2.
Right now I don't have other explanations..

**Comment by deepiksdev** [comment]
@Lolitawxc OK, thanks. Please make more precise tests for us to understand.

**Comment by Lolitawxc** [comment]
@deepiksdev with the exact sames images for style and content I got 2min54 on my local machine (against 8min36). I will make more tests to see if we stay in the 7-10 min range instead of the 3-5 min range we expected.

**Comment by Lolitawxc** [comment]
@deepiksdev  I tried with a g2**8 instance and it was worse: 10min36

**Comment by deepiksdev** [comment]
@Lolitawxc As mentioned in a private message, the Oscar App takes a few seconds to generate a 1024x1024 image, for example this one
![image1](https://cloud.githubusercontent.com/assets/2860170/16947189/e91f140a-4dad-11e6-8b65-2fcb34a31ada.JPG)

**Comment by Lolitawxc** [comment]
@deepiksdev I launched a g2 * 2 instace with tensorflow GPU installed and managed to make https://github.com/yusuketomoto/chainer-fast-neuralstyle work but not with GPU.
The devs obtain on a particular sample:
-2s with a good CPU
-0.4s with a good GPU (titan X)

For me on  this particular sample it took 3min05s (but again I was not using the CPU on the GPU instance so the CPU was probably very poor).

I think I should be able to make the GPU version work within the day.

A few notes though:
- Compared to the slow version, you cannot give any photo as a style photo, you have to train a model with a style photo, so the photos you want to use a modifiers have to be given in advance, so 
that I can train the model
- I have no idea how much time it takes to train a model with this CNN, maybe a few minutes, a few hours, or days (the one I used to test was the only trained model given 'starry night')
- we won't get the 0.4s because as I wrote, they use a titan X and to me the GPU instances from amazon are much slower (on the other hand, I think their good CPU instances might beat the 2s).
Anyway we should be able to be into the several seconds range (I will try with different CPU/GPU instances and give you the results)

**Comment by Lolitawxc** [comment]
@deepiksdev 
> For me on this particular sample 
A 512 * 384 image if you wonder

**Comment by Lolitawxc** [comment]
@deepiksdev 
with the same 512 * 384 image:
- m4.large: 82s

**Comment by deepiksdev** [comment]
@Lolitawxc Here is a gist to install chainer with GPU: https://gist.github.com/pyr-revs/31dba1c9aeff575f58b9

**Comment by Lolitawxc** [comment]
@deepiksdev I created an image with fast Neural Style working with GPU enabled: ami-c326a9d4
It takes 17s on a g 2 * 2 image of 1024*768

**Comment by Lolitawxc** [comment]
@deepiksdev To launch in gpu mode, use the following command:
python generate.py --gpu 0 sample_images/tubingen.jpg -m models/composition.model -o sample_images/output.jpg

**Comment by Lolitawxc** [comment]
@deepiksdev  I launched the training of a first model 'traversed lines'.
The training for each model should take around 44 hours if I refer to this comment:
https://github.com/yusuketomoto/chainer-fast-neuralstyle/issues/1#issuecomment-231638046
The gpu on amazon is not as good as his gtx 970 so in one way it should take longer, but the 44hours have been achieved with the 512px technique (read the comment to understand) and I used the 256*256.
I might have the glitches as in the first photo he shows but I don't understand completely the 512 px technique and since the code has been changed lately I am hoping that I won't get the glitches.
If I get results that are similar to the first photo, I will retrain the model with what I understood of the 512px technique and see if I get the results of the second photo.

**Comment by deepiksdev** [comment]
@Lolitawxc The comment is indeed hard to understand.

**Comment by deepiksdev** [comment]
Continued in https://github.com/deepiksdev/chainer/issues/1

**Comment by deepiksdev** [comment]
It would be interesting to reimplement this in addition to chainer.

**Comment by deepiksdev** [comment]
No longer relevant

**Comment by deepiksdev** [comment]
No longer relevant
