### ISSUE TITLE
Implement Face Recognition

### ISSUE THREAD

**Issue by deepiksdev** [deepiksdev/torch#10]
See https://medium.com/@ageitgey/machine-learning-is-fun-part-4-modern-face-recognition-with-deep-learning-c3cffc121d78#.y51ut0nnb

**Comment by Lolitawxc** [comment]
@deepiksdev  I need more precisions about this.
Since there is a training part (and I don't know how much time it will take), I need to know who we want to recognize.
As already mentionned, it works well because the search is among a restricted set (several thousands at worst).
Do I only recognize famous people ? In that case I need to build a dataset with several thousands of famous people with 10 photos for each person (the paper says it should be enough).
As already mentionned, it means that if there is a new famous person, this person won't be recognized.

**Comment by deepiksdev** [comment]
@Lolitawxc 

> Since there is a training part (and I don't know how much time it will take), 

I don't understand this. The paper mentions that "Lucky for us, the fine folks at OpenFace already did this and they published several trained networks which we can directly use" [...] "So all we need to do ourselves is run our face images through their pre-trained network to get the 128 measurements for each face"

> I need to know who we want to recognize.

We will discuss that later. First we need to understand how and how well this works, using examples they provide. Otherwise, we can use the Caia or Storimage databases.

**Comment by Lolitawxc** [comment]
@deepiksdev  
> I don't understand this. The paper mentions that "Lucky for us, the fine folks at OpenFace already did this and they published several trained networks which we can directly use" [...] "So all we need to do ourselves is run our face images through their pre-trained network to get the 128 measurements for each face"

I am asking regarding the SVM (see Part 4) not the CNN (though we agree it should not take as much as a CNN).

> We will discuss that later. First we need to understand how and how well this works, using examples they provide. Otherwise, we can use the Caia or Storimage databases.

Caia or Storimage won't do. I need several images of the same person. I will take theirs or make my own dataset until you give me exactly who we want to recognize.

**Comment by deepiksdev** [comment]
Not relevant for us
